# Generated by Django 6.0.4 on 2026-05-05 08:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days_per_month', models.IntegerField(default=22)),
                ('shift_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('shift_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('late_deduction_rate_per_minute', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('insurance_percentage', models.DecimalField(decimal_places=4, default=0.05, help_text='e.g., 0.05 for 5%', max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=4, default=0.15, help_text='e.g., 0.15 for 15%', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyDeductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('penalties', models.DecimalField(decimal_places=2, default=0, help_text='Manual disciplinary penalties', max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_deductions', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Monthly Deductions',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('variable_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_increment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_earnings', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Monthly Earnings',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Paid', 'Paid')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
