# Generated by Django 6.0.4 on 2026-05-05 11:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_join_date_employee_status'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyearnings',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlyearnings',
            name='employee',
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Late', 'Late'), ('Loan', 'Loan'), ('Penalty', 'Penalty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bonus', 'Bonus'), ('Overtime', 'Overtime'), ('Allowance', 'Allowance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='employees.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyDeductions',
        ),
        migrations.DeleteModel(
            name='MonthlyEarnings',
        ),
    ]
