# Generated by Django 6.0.3 on 2026-05-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_monthlyearnings_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='type',
            field=models.CharField(choices=[('Absence', 'Absence Deduction'), ('Late', 'Late Coming'), ('Penalty', 'Disciplinary Penalty'), ('Insurance', 'Social Insurance'), ('Tax', 'Income Tax'), ('Loan', 'Loan Repayment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='earning',
            name='type',
            field=models.CharField(choices=[('Bonus', 'Performance Bonus'), ('Overtime', 'Overtime Pay'), ('Commission', 'Sales Commission'), ('Allowance', 'General Allowance'), ('Housing', 'Housing Allowance'), ('Transport', 'Transport Allowance')], max_length=20),
        ),
    ]
