# Generated by Django 6.0.3 on 2026-05-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_branch_code'),
        ('payroll', '0003_alter_deduction_type_alter_earning_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='branch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='accounts.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='grace_period_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='insurance_percentage',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=4, default=0.15, max_digits=5),
        ),
    ]
