# Generated by Django 6.0.3 on 2026-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_systemconfiguration_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='attendance_absence_deduction',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='attendance_late_deduction',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='loan_installment_deduction',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_earnings',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
