# Generated by Django 6.0.4 on 2026-05-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog_ip_address_user_email_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
