# Generated by Django 6.0.3 on 2026-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(default='00', max_length=5, unique=True),
        ),
    ]
