# Generated by Django 6.0.3 on 2026-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_join_date_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_number',
            field=models.CharField(blank=True, help_text='IBAN or Bank Account Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='requires_attendance_tracking',
            field=models.BooleanField(default=True, help_text='Uncheck if this employee is exempt from fingerprint/scanner attendance tracking'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, help_text='Unique employee identifier (auto-generated)', max_length=20, unique=True),
        ),
    ]
