# Generated by Django 6.0.3 on 2026-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_department_branch_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='department',
            name='branch',
        ),
    ]
