# Generated by Django 6.0.3 on 2026-05-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_branch_code'),
        ('zkteco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zktecodevice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zkteco_devices', to='accounts.branch'),
        ),
    ]
